version: 2

models:
  - name: int_orders_enriched
    description: "Tabela intermediária que enriquece os pedidos (SalesOrderHeader) com dados de clientes e cartões de crédito"
    columns:
      - name: sales_order_id
        description: "Chave primária do pedido"
        tests:
          - not_null
          - unique
      - name: customer_id
        description: "Chave estrangeira do cliente"
        tests:
          - not_null
      - name: person_id
        description: "Identificador da pessoa associada ao cliente"
      - name: credit_card_id
        description: "Chave estrangeira do cartão de crédito"
      - name: card_type
        description: "Tipo do cartão de crédito (ex.: Visa, MasterCard)"
      - name: status
        description: "Status do pedido (1=Em processo; 2=Aprovado; 3=Em espera; 4=Rejeitado; 5=Enviado; 6=Cancelado)"
      - name: total_due
        description: "Valor total do pedido incluindo impostos e frete"
      - name: order_date
        description: "Data do pedido"
      - name: ship_date
        description: "Data de envio do pedido"

  - name: int_order_items_enriched
    description: "Tabela intermediária que enriquece os itens do pedido com informações de produtos e valores"
    columns:
      - name: sales_order_detail_id
        description: "Chave primária do detalhe do pedido"
        tests:
          - not_null
          - unique
      - name: sales_order_id
        description: "Chave estrangeira do pedido"
        tests:
          - not_null
      - name: product_id
        description: "Chave estrangeira do produto"
        tests:
          - not_null
      - name: product_name
        description: "Nome do produto"
      - name: list_price
        description: "Preço de lista do produto"
      - name: standard_cost
        description: "Custo padrão do produto"
      - name: order_qty
        description: "Quantidade de itens comprados no pedido"
      - name: unit_price
        description: "Preço unitário do produto"
      - name: unit_price_discount
        description: "Desconto aplicado no preço unitário"
      - name: total_item_value
        description: "Valor total líquido do item (quantidade * (preço unitário - desconto))"

  - name: int_orders_with_reason
    description: "Tabela intermediária que associa pedidos aos motivos da venda"
    columns:
      - name: sales_order_id
        description: "Chave estrangeira do pedido"
        tests:
          - not_null
      - name: salesreasonid
        description: "Chave primária do motivo da venda"
        tests:
          - not_null
      - name: sales_reason
        description: "Descrição do motivo da venda"

  - name: int_orders_final
    description: "Tabela final intermediária que combina pedidos, itens e motivos da venda"
    columns:
      - name: sales_order_id
        description: "Chave primária do pedido"
        tests:
          - not_null
      - name: sales_order_detail_id
        description: "Chave primária do detalhe do pedido"
        tests:
          - not_null
      - name: customer_id
        description: "Chave estrangeira do cliente"
        tests:
          - not_null
      - name: product_id
        description: "Chave estrangeira do produto"
        tests:
          - not_null
      - name: product_name
        description: "Nome do produto"
      - name: card_type
        description: "Tipo do cartão de crédito usado no pedido"
      - name: status
        description: "Status do pedido"
      - name: total_due
        description: "Valor total do pedido"
      - name: order_date
        description: "Data do pedido"
      - name: ship_date
        description: "Data de envio"
      - name: order_qty
        description: "Quantidade comprada do item"
      - name: unit_price
        description: "Preço unitário"
      - name: unit_price_discount
        description: "Desconto unitário"
      - name: total_item_value
        description: "Valor total líquido do item"
      - name: sales_reason
        description: "Motivo da venda"
